from typing import Protocol, Callable, Any

class Transport(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def publish(self, topic: str, payload: dict, retain: bool = False, qos: int = 1) -> None: ...
    def subscribe(self, topic: str, callback: Callable[[str, dict], None]) -> None: ...
