import os
import ast
from pathlib import Path

def get_imports(file_path):
    imports = set()
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read())
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for n in node.names:
                    imports.add(n.name.split('.')[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split('.')[0])
    except Exception as e:
        pass
    return imports

def main():
    root = Path(".")
    entry_points = list(root.glob("experiments/*.py")) + list(root.glob("tests/*.py"))
    
    reachable = set()
    to_visit = []
    
    # Initial imports from entry points
    for ep in entry_points:
        imports = get_imports(ep)
        for imp in imports:
            if imp not in reachable:
                reachable.add(imp)
                to_visit.append(imp)
                
    # Basic transitive closure for local packages
    visited = set()
    while to_visit:
        pkg = to_visit.pop(0)
        if pkg in visited:
            continue
        visited.add(pkg)
        
        pkg_path = root / pkg
        if pkg_path.is_dir():
            for py_file in pkg_path.rglob("*.py"):
                imports = get_imports(py_file)
                for imp in imports:
                    if imp not in reachable:
                        reachable.add(imp)
                        to_visit.append(imp)

    legacy_dirs = ["controller", "digital_twin", "forecasting", "telemetry", "metrics", "scenarios", "simulator", "validation", "data", "dashboard", "ui"]
    root_scripts = ["run_live.py", "run_experiment.py", "run_disasters.py"]
    
    with open("docs/CODEMAP.md", "w", encoding="utf-8") as out:
        out.write("# GridGuard Code Map\n\n")
        out.write("This map is generated by `tools/codemap.py`.\n\n")
        
        out.write("## Top-Level Directories\n\n")
        
        all_dirs = [d.name for d in root.iterdir() if d.is_dir() and not d.name.startswith(".")]
        all_dirs = [d for d in all_dirs if d not in ["venv", "docs", "tools", "__pycache__", "results", "models"]]
        
        for d in sorted(all_dirs):
            status = "used" if d in reachable else "legacy (not reachable from current experiments)"
            if d in legacy_dirs and d not in reachable:
                status = "legacy (not reachable from current experiments)"
            out.write(f"- `{d}/`: {status}\n")
            
        out.write("\n## Root Scripts\n\n")
        for s in root_scripts:
            # Check if used - root scripts are usually entry points themselves, but spec asks to mark them as legacy if they aren't part of experiments/tests
            # They are not reachable from experiments/tests.
            out.write(f"- `{s}`: legacy (not reachable from current experiments)\n")

if __name__ == "__main__":
    main()
